version: '3.1'

volumes:
#  prometheus_data: {}
  grafana-storage: {}

services:
  redis:
    image: redis:alpine
    ports:
    - 6379:6379
    network_mode: "host"

  consul:
    image: consul:latest
    ports:
      - 8500:8500
    network_mode: "host"


  #    environment:
#      CONSUL_BIND_INTERFACE: eth0

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    depends_on:
      - consul
    volumes:
      - ./:/etc/prometheus/
    network_mode: "host"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    user: "104"
    volumes:
      - grafana-storage:/var/lib/grafana
    network_mode: "host"