global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'consul'

    metrics_path: '/actuator/prometheus'

    consul_sd_configs:
      - server: 'localhost:8500'
        scheme: http