spring:
  application:
    name: beer-service

  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false

management:
  endpoints:
    web:
      exposure:
        include: ["*"]
#        include: ["info", "health", "prometheus", "chaosmonkey"]
  metrics:
    tags:
      region: us-west-1
      stack: chaos
      env: prod
      application-name: ${spring.application.name}
  endpoint:
    chaosmonkey:
      enabled: true

---
spring:
  profiles:
    active: chaos-monkey
chaos:
  monkey:
    enabled: true
    watcher:
      component: false
      controller: false
      repository: false
      rest-controller: true
      service: false
    assaults:
      latency-active: true
      latency-range-start: 2000
      latency-range-end: 5000
      exceptions-active: true
